# Generated by Django 4.1.7 on 2023-03-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(upload_to='uploads/')),
                ('my_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
